spring:
  profiles: dev1
  name: webcrm
  datasource:
    driverClassName: org.firebirdsql.jdbc.FBDriver
    url: jdbc:firebirdsql:localhost/3050:d:/dev/fbdb/webcrm.fdb?sqlDialect=3;charSet=UTF-8;Role=;Connection lifetime=15;pooling=true;blobBufferSize=8192;type=TYPE2
    username: coretree
    password: core9158
server:
  port: ${port:80}
  session-timeout: 1800
uc:
  pbxip: 14.63.168.129
  
---

spring:
  profiles: dev2
  name: webcrm
  datasource:
    driverClassName: org.firebirdsql.jdbc.FBDriver
    url: jdbc:firebirdsql://localhost:3050/d:/dev/fbdb/webcrm.fdb?sqlDialect=3;charSet=UTF-8;Role=;Connection lifetime=15;pooling=true;blobBufferSize=8192;type=TYPE2
    username: coretree
    password: core9158
server:
  port: ${port:8080}
  session-timeout: 1800
uc:
  pbxip: 14.63.171.190
  
---

spring:
  profiles: dev3
  name: webcrm
  datasource:
    driverClassName: org.firebirdsql.jdbc.FBDriver
    url: jdbc:firebirdsql://localhost:3050/d:/dev/fbdb/webcrm.fdb?sqlDialect=3;charSet=UTF-8;Role=;Connection lifetime=15;pooling=true;blobBufferSize=8192;type=TYPE2
    username: coretree
    password: core9158
server:
  port: ${port:8080}
  session-timeout: 1800
uc:
  pbxip: 14.63.166.98
  
---

spring:
  profiles: local
  name: webcrm
  datasource:
    driverClassName: org.firebirdsql.jdbc.FBDriver
    url: jdbc:firebirdsql://localhost:3050//opt/webcrm/db/WEBCRM.FDB?sqlDialect=3;charSet=UTF-8;Role=;Connection lifetime=15;pooling=true;blobBufferSize=8192;type=TYPE2
    username: coretree
    password: core9158
server:
  port: ${port:80}
  session-timeout: 1800
uc:
  pbxip: 127.0.0.1

---

spring:
  profiles: remote
  name: webcrm
  datasource:
    driverClassName: org.firebirdsql.jdbc.FBDriver
    url: jdbc:firebirdsql://${dbserver:localhost}:3050/${dbpath:/opt/webcrm/db/WEBCRM.FDB}?sqlDialect=3;charSet=UTF-8;Role=;Connection lifetime=15;pooling=true;blobBufferSize=8192;type=TYPE2
    username: coretree
    password: core9158
server:
  port: ${port:80}
  session-timeout: 1800
uc:
  pbxip: ${pbxip:127.0.0.1}
